name: Deploy AWS Lambdas

on:
  push:
    branches:
      - main  # Desplegar cuando se realicen cambios en la rama principal

jobs:
  deploy-simple-greeting:
    name: Deploy Simple Greeting Lambda
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Zip Lambda Function - Simple Greeting
      run: |
        mkdir -p zip
        zip -j zip/simple_greeting.zip lambdas/simple_greeting.py

    - name: Deploy Lambda Function - Simple Greeting
      run: |
        aws lambda update-function-code \
          --function-name simple_greeting \
          --zip-file fileb://zip/simple_greeting.zip \
          --region us-east-1

    - name: Verify Deployment - Simple Greeting
      run: |
        aws lambda get-function \
          --function-name simple_greeting

  deploy-personalized-greeting:
    name: Deploy Personalized Greeting Lambda
    runs-on: ubuntu-latest
    needs: deploy-simple-greeting  # Ejecutar después de SaludoSimple
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Zip Lambda Function - Personalized Greeting
      run: |
        mkdir -p zip
        zip -j zip/personalized_greeting.zip lambdas/personalized_greeting.py

    - name: Deploy Lambda Function - Personalized Greeting
      run: |
        aws lambda update-function-code \
          --function-name personalized_greeting \
          --zip-file fileb://zip/personalized_greeting.zip \
          --region us-east-1

    - name: Verify Deployment - Personalized Greeting
      run: |
        aws lambda get-function \
          --function-name personalized_greeting

  deploy-basic-calculator:
    name: Deploy Basic Calculator Lambda
    runs-on: ubuntu-latest
    needs: deploy-personalized-greeting  # Ejecutar después de SaludoPersonalizado
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Zip Lambda Function - Basic Calculator
      run: |
        mkdir -p zip
        zip -j zip/basic_calculator.zip lambdas/basic_calculator.py

    - name: Deploy Lambda Function - Basic Calculator
      run: |
        aws lambda update-function-code \
          --function-name BasicCalculator \
          --zip-file fileb://zip/basic_calculator.zip \
          --region us-east-1

    - name: Verify Deployment - Basic Calculator
      run: |
        aws lambda get-function \
          --function-name BasicCalculator
